### ISSUE TITLE
Изменить верстку гостевой книги

### ISSUE THREAD

**Issue by visavi** [visavi/rotor#106]
Без использования стилей сайта, только на стилях bootstrap

**Comment by sy2nyk** [comment]
По примеру форума делать?

**Comment by visavi** [comment]
на форуме сейчас точно также как и в гостевой и на всем сайте, нужно новую верстку на bootstrap делать

**Comment by visavi** [comment]
Вообще лучше это сделать отдельным простым шаблоном, на обычной html странице, нужно потом будет посмотреть чтобы все элементы вписывались нормально, тогда уже можно будет внедрить во все файлы

**Comment by vaninanton** [comment]
Есть ли отдельный шаблон готовый? Я бы посмотрел

**Comment by visavi** [comment]
Готово, уже в мастере
