### ISSUE TITLE
PHPDOC

### ISSUE THREAD

**Issue by mr-molodoy** [visavi/rotor#15]
Будет ли использование PHPDOC в проекте? В первую очередь работать с моделями не удобно - в eloquent и без того большинство методов работают через маг. вызовы - приходится мучится с автокомплитом в IDE. А тут, вовсе при работе с моделями - phpStorm как на дурака смотрит )

**Comment by visavi** [comment]
Чтобы нормально работало нужно добавлять метод query(), тогда автокомплиты работать будут 
к примеру $user = User::query()->find(1);
Потихоньку  я привожу код к такому виду
А так все методы конечно описываются по всем правилам

**Comment by visavi** [comment]
![2017-09-19 15-49-39](https://user-images.githubusercontent.com/826831/30593122-33302a94-9d52-11e7-97fd-153f09bad7d0.png)
А так задача по описанию методов в app/helpers.php уже есть, если имеется время, то жду коммиты
