### ISSUE TITLE
Использование isAdmin()

### ISSUE THREAD

**Issue by akimitsu-bm** [visavi/rotor#49]
Решил попробовать некоторые скрипты из админки перенести и возник вопрос.

Например мне надо ссылку в шаблоне скрыть по уровню пользователя, как в таком случае правильнее использовать функцию isAdmin()?
Напрямую в шаблоне или лучше через переменную в контроллере (как на главной странице админки) и уже ее вызывать в шаблоне?

**Comment by visavi** [comment]
Да, можно прямо в шаблоне вызвать
просто isAdmin()  или к примеру isAdmin('moder')  тогда уровень доступа будет от модера и выше

**Comment by visavi** [comment]
на главной админки я потом уберу и сделаю в шаблоне

**Comment by akimitsu-bm** [comment]
Ок, спасибо.
