### ISSUE TITLE
Придумать где очищать сессию ошибок валидации

### ISSUE THREAD

**Issue by visavi** [visavi/rotor#54]
Ошибки валидации записываются в сессию
раньше ошибки удалялись в footere, внизу страницы, а при переадресации footer не вызывался
сейчас при вызове getInput($name)  удаляется запись из сессии
минусы в том, что иногда getInput($name) нужно проверять несколько раз
и приходится записывать значение в переменную, что не очень удобно
Пробовал в деструктор базового класса, но тогда при переадресации данные уже удаляются
может есть какой-нибудь еще способ?

**Comment by KpuTuK** [comment]
как насчет того чтобы при наличие ошибки добавлять в url ?errorClear а уже в экшене внизу его удалять при наличии get с errorClear

**Comment by visavi** [comment]
В принципе текущий способ вполне нормальный, вроде все стабильно работает, так что думаю задачу можно закрыть

**Comment by visavi** [comment]
KpuTuK ты кстати звезду нажал у другого проекта visavi/rotorcms, а он уже устарел 
сейчас все тут разрабатываем https://github.com/visavi/rotor

**Comment by KpuTuK** [comment]
время будет тоже подключусь
