### ISSUE TITLE
Ошибка при Seed

### ISSUE THREAD

**Issue by sy2nyk** [visavi/rotor#7]
В сиде NoticeSeeder нужно добавить user_id и updated_at

**Comment by sy2nyk** [comment]
Или добавить дефолтные значения в саму таблицу

**Comment by sy2nyk** [comment]
![image](https://user-images.githubusercontent.com/2834652/29816777-277fcae6-8cbe-11e7-9f44-79a020b5ec8e.png)

**Comment by visavi** [comment]
Сейчас сделаю

**Comment by visavi** [comment]
https://github.com/visavi/rotor/commit/e3175a5e32be5a05733f94c7a669b9c3363cd718
